networks:
  secure_ledger_mesh:
    driver: bridge

volumes:
  ledger_state_1:
  ledger_state_2:
  ledger_state_3:

services:
  # Nó Bootstrap (A âncora da rede e o Minerador)
  ledger-miner-1:
    build: .
    container_name: ledger-miner-1
    environment:
      - LEDGER_MINING=1
      - LEDGER_P2P_PORT=4004
      - LEDGER_API_PORT=8080
    volumes:
      - ledger_state_1:/data/ledger
    networks:
      - secure_ledger_mesh
    ports:
      - "4004:4004"
      - "8080:8080"
    stdin_open: true # Mantém o terminal aberto para a CLI
    tty: true        # Emula um terminal real

  # Nó 2 (Liga-se ao Nó 1 - Não Minera)
  ledger-miner-2:
    build: .
    container_name: ledger-miner-2
    environment:
      - LEDGER_MINING=0
      - LEDGER_P2P_PORT=4005
      - LEDGER_PEERS=ledger-miner-1:4004
      - LEDGER_API_PORT=8081
    volumes:
      - ledger_state_2:/data/ledger
    networks:
      - secure_ledger_mesh
    ports:
      - "4005:4005"
      - "8081:8080"
    depends_on:
      - ledger-miner-1
    stdin_open: true
    tty: true

  # Nó 3 (Liga-se ao Nó 2 - Não Minera)
  ledger-miner-3:
    build: .
    container_name: ledger-miner-3
    environment:
      - LEDGER_MINING=0
      - LEDGER_P2P_PORT=4006
      - LEDGER_PEERS=ledger-miner-2:4005 # O nome do serviço no compose!
      - LEDGER_API_PORT=8082
    volumes:
      - ledger_state_3:/data/ledger
    networks:
      - secure_ledger_mesh
    ports:
      - "4006:4006"
      - "8082:8080"
    depends_on:
      - ledger-miner-2
    stdin_open: true
    tty: true