#!/usr/bin/env python3
"""
Parser + Snort rule generator (fixed file-reading to support fh.tell()).
"""
import argparse, json, re, sqlite3, os
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse 
from ioc_classifier import IoC_Classifier

URL_RE = re.compile(r"https?://[^\s'\"<>]+", re.IGNORECASE)
IP_RE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
SUSP_CMDS = ["wget", "curl", "rm -rf", "busybox", "nc", "netcat", "python -c", "perl -e", "bash -i", "chmod 777", "curl -fsSL"]
OFFSET_FILE = ".cowrie_parser.offset"
START_SID = 1000000

def init_db(conn):
    c = conn.cursor()
    c.execute("""CREATE TABLE IF NOT EXISTS iocs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        type TEXT NOT NULL,
        value TEXT NOT NULL,
        first_seen TEXT NOT NULL,
        last_seen TEXT NOT NULL,
        count INTEGER DEFAULT 1,
        source TEXT NOT NULL,
        note TEXT,
        sid INTEGER,
        severity TEXT DEFAULT 'MEDIUM',
        UNIQUE(type, value)
    )""")
    conn.commit()

def upsert_ioc(conn, typ, value, source='cowrie', note=None, classifier=None):
    now = datetime.utcnow().isoformat()
    c = conn.cursor()
    
    # Check if IoC already exists WITH THE SAME TYPE
    c.execute("SELECT count FROM iocs WHERE value=? AND type=?", (value, typ))
    row = c.fetchone()
    
    if row:
        # IoC EXISTS (same type) - increment count and RE-CLASSIFY
        new_count = row[0] + 1
        
        # Re-classify with NEW count
        if classifier:
            severity, reason = classifier.classify(typ, value, new_count, source)
            # Para usernames, SEMPRE usa o reason do classifier (ignora note)
            if typ == 'username':
                final_note = reason
            else:
                final_note = note if note else reason
        else:
            severity = 'MEDIUM'
            final_note = note or ''
        
        c.execute("""
            UPDATE iocs 
            SET last_seen=?, count=?, note=?, severity=?
            WHERE value=? AND type=?
        """, (now, new_count, final_note, severity, value, typ))
        conn.commit()
        return False
    
    else:
        # NEW IoC - classify with count=1
        if classifier:
            severity, reason = classifier.classify(typ, value, 1, source)
            # Para usernames, SEMPRE usa o reason do classifier
            if typ == 'username':
                final_note = reason
            else:
                final_note = note if note else reason
        else:
            severity = 'MEDIUM'
            final_note = note or ''
        
        try:
            c.execute("""
                INSERT INTO iocs(type, value, first_seen, last_seen, count, source, note, severity) 
                VALUES (?, ?, ?, ?, 1, ?, ?, ?)
            """, (typ, value, now, now, source, final_note, severity))
            conn.commit()
            return True
        except sqlite3.IntegrityError:
            # Já existe, mas com tipo diferente - ignorar
            return False

def assign_sids(conn, start_sid=START_SID):
    c = conn.cursor()
    c.execute("SELECT MAX(sid) FROM iocs")
    r = c.fetchone()
    maxsid = r[0] or (start_sid - 1)
    c.execute("SELECT id FROM iocs WHERE sid IS NULL ORDER BY first_seen")
    rows = c.fetchall()
    sid = maxsid + 1
    for (rid,) in rows:
        c.execute("UPDATE iocs SET sid=? WHERE id=?", (sid, rid))
        sid += 1
    conn.commit()

def escape_for_snort(s):
    if s is None:
        return ""
    return s.replace('"','\\"')

def generate_rules(conn, outpath):
    c = conn.cursor()
    c.execute("SELECT type,value,sid,severity FROM iocs ORDER BY id")
    rows = c.fetchall()
    
    classifier = IoC_Classifier()
    rules = ["# Generated by cowrie_parser_and_snortgen.py\n"]
    
    for typ, val, sid, severity in rows:
        if not sid or not val or str(val).strip() == "":
            continue
        
        safe = str(val).replace('"','')
        priority = classifier.get_snort_priority(severity or 'MEDIUM')
        
        if typ == "ip":
            rule = (f'alert ip {safe} any -> $HOME_NET any '
                    f'(msg:"[{severity}] Cowrie: malicious IP {safe}"; '
                    f'priority:{priority}; '
                    f'sid:{sid}; rev:1; classtype:trojan-activity;)\n')
            rules.append(rule)
            
        elif typ == "url":
            rule = (f'alert tcp $HOME_NET any -> any 80 '
                    f'(msg:"[{severity}] Cowrie: download URL {safe}"; '
                    f'flow:established,to_server; content:"{safe}"; http_header; nocase; '
                    f'priority:{priority}; '
                    f'sid:{sid}; rev:1; classtype:trojan-activity;)\n')
            rules.append(rule)
            
        elif typ == "command":
            if safe.strip().lower() in ("","exit","ls","pwd"):
                continue
            rule = (f'alert tcp any any -> $HOME_NET any '
                    f'(msg:"[{severity}] Cowrie: suspicious command"; '
                    f'content:"{escape_for_snort(safe)}"; nocase; '
                    f'priority:{priority}; '
                    f'sid:{sid}; rev:1; classtype:trojan-activity;)\n')
            rules.append(rule)
            
        elif typ in ("password","username"):
            rule = (f'alert tcp any any -> $HOME_NET any '
                    f'(msg:"[{severity}] Cowrie: observed {typ}"; '
                    f'content:"{escape_for_snort(safe)}"; nocase; '
                    f'priority:{priority}; '
                    f'sid:{sid}; rev:1; classtype:trojan-activity;)\n')
            rules.append(rule)
        else:
            rule = (f'alert tcp any any -> $HOME_NET any '
                    f'(msg:"[{severity}] Cowrie: IoC detected"; '
                    f'content:"{escape_for_snort(safe)}"; nocase; '
                    f'priority:{priority}; '
                    f'sid:{sid}; rev:1; classtype:trojan-activity;)\n')
            rules.append(rule)

    os.makedirs(os.path.dirname(outpath), exist_ok=True)
    with open(outpath, "w") as f:
        f.writelines(rules)
    print(f"Wrote {len(rules)-1} IoC rules (with severity) to {outpath}")

def process_log(conn, logfile):
    classifier = IoC_Classifier()
    # read offset
    offset = 0
    if os.path.exists(OFFSET_FILE):
        try:
            offset = int(open(OFFSET_FILE).read().strip())
        except:
            offset = 0

    new_offset = offset
    added = 0

    # open file in text mode and use readline() so fh.tell() is allowed
    with open(logfile, "r", encoding="utf-8", errors="ignore") as fh:
        fh.seek(offset)
        while True:
            line = fh.readline()
            if not line:
                break
            new_offset = fh.tell()
            line = line.strip()
            if not line:
                continue
            try:
                j = json.loads(line)
            except Exception:
                continue

            # src_ip
            src_ip = j.get("src_ip")
            if src_ip and IP_RE.search(str(src_ip)):
                if upsert_ioc(conn, "ip", src_ip, classifier=classifier):
                    added += 1

            # username/password
            if "username" in j and "password" in j:
                user = j.get("username")
                pwd = j.get("password")
                if user:
                    if upsert_ioc(conn, "username", user, classifier=classifier):  # ← SEM note aqui!
                        added += 1
                if pwd:
                    if upsert_ioc(conn, "password", pwd, note=f"user:{user}", classifier=classifier):  # ← COM note aqui
                        added += 1

            # input/command
            cmd = j.get("input") or j.get("message") or j.get("command") or ""
            if cmd:
                for s in SUSP_CMDS:
                    if s.lower() in cmd.lower():
                        if upsert_ioc(conn, "command", cmd, note=s, classifier=classifier):
                            added += 1
                for u in URL_RE.findall(str(cmd)):
                    parsed = urlparse(u)
                    host = parsed.netloc or u
                    if upsert_ioc(conn, "url", host, classifier=classifier):
                        added += 1

            # url field
            urlf = j.get("url")
            if urlf:
                if URL_RE.search(str(urlf)):
                    for u in URL_RE.findall(str(urlf)):
                        if upsert_ioc(conn, "url", u, classifier=classifier):
                            added += 1
                else:
                    parsed = urlparse(urlf)
                    host = parsed.netloc or urlf
                    if upsert_ioc(conn, "url", host, classifier=classifier):
                        added += 1

    with open(OFFSET_FILE, "w") as of:
        of.write(str(new_offset))

    print(f"Processed log. New offset {new_offset}. New IoCs added: {added}")
    return added

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--log", required=True, help="path to cowrie.json")
    ap.add_argument("--db", default="cowrie_iocs.db")
    ap.add_argument("--out", default="snort/cowrie_autogen.rules")
    ap.add_argument("--sid-start", type=int, default=START_SID)
    args = ap.parse_args()

    if not os.path.exists(args.log):
        print("Log file not found:", args.log)
        return

    conn = sqlite3.connect(args.db)
    init_db(conn)
    process_log(conn, args.log)
    assign_sids(conn, args.sid_start)
    generate_rules(conn, args.out)
    conn.close()

if __name__ == "__main__":
    main()
